
(()=>{
"use strict";
const C=HobileCore,$=id=>document.getElementById(id),canvas=$("game"),ctx=canvas.getContext("2d",{alpha:false});
let W=0,H=0,DPR=1,last=0,running=false,paused=false,server="TRAINING",team="CT",ctScore=0,tScore=0,roundTime=105,bombPlanted=false,bombTimer=0,bomb=null,ending=false,lastShot=0;
const FOV=Math.PI/3,STRIP=3;
let assets={},player,bots=[],input={jx:0,jy:0},weaponIndex=0;
const weapons=[
 {name:"VX-9 RIFLE",img:"rifle",mag:30,reserve:90,rate:120,damage:37,head:100,range:16},
 {name:"P9 SIDEARM",img:"pistol",mag:15,reserve:45,rate:260,damage:29,head:86,range:12},
 {name:"TACTICAL KNIFE",img:"knife",mag:0,reserve:0,rate:430,damage:60,head:100,range:1.35}
];
function resize(){DPR=Math.min(devicePixelRatio||1,1.5);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener("resize",resize);resize();
["contextmenu","selectstart","dragstart","gesturestart","gesturechange","gestureend"].forEach(ev=>document.addEventListener(ev,e=>e.preventDefault(),{passive:false}));document.addEventListener("touchmove",e=>{if(running)e.preventDefault()},{passive:false});document.addEventListener("dblclick",e=>e.preventDefault(),{passive:false});
function preload(){let files={sand:"assets/wall_sand.png",concrete:"assets/wall_concrete.png",metal:"assets/wall_metal.png",crate:"assets/crate.png",ct:"assets/ct_soldier.png",t:"assets/t_soldier.png",rifle:"assets/rifle_fp.png",pistol:"assets/pistol_fp.png",knife:"assets/knife_fp.png",bomb:"assets/bomb.png"};return Promise.all(Object.entries(files).map(([k,src])=>new Promise((res,rej)=>{let im=new Image();im.onload=()=>{assets[k]=im;res()};im.onerror=rej;im.src=src})))}
const portal=$("portal"),teams=$("teams"),loading=$("loading"),hud=$("hud"),controls=$("controls"),modal=$("modal");
function openModal(t,b){$("modalTitle").textContent=t;$("modalBody").innerHTML=b;modal.classList.remove("hidden")} $("modalClose").onclick=()=>modal.classList.add("hidden");
$("create").onclick=()=>{let code=Math.random().toString(36).slice(2,6).toUpperCase();openModal("CREATE ROOM",`<p style="opacity:.6">Share this code:</p><div class="roomcode">${code}</div><button id="host" class="primary">HOST ROOM</button>`);setTimeout(()=>{$("host").onclick=()=>{server="ROOM-"+code;modal.classList.add("hidden");chooseTeam()}},0)};
$("joinRoom").onclick=()=>openModal("JOIN ROOM",`<p style="opacity:.6">Online synchronization comes in the multiplayer milestone. Bot matches are playable now.</p>`);
$("browse").onclick=()=>$("serverTitle").scrollIntoView({behavior:"smooth"});$("quick").onclick=()=>{server="EU-01";chooseTeam()};$("training").onclick=()=>{server="TRAINING";chooseTeam()};document.querySelectorAll(".joinBtn").forEach(b=>b.onclick=()=>{server=b.dataset.server;chooseTeam()});
function chooseTeam(){portal.classList.add("hidden");teams.classList.remove("hidden")} document.querySelectorAll("[data-team]").forEach(b=>b.onclick=()=>{team=b.dataset.team;teams.classList.add("hidden");startLoading()});
async function startLoading(){loading.classList.remove("hidden");$("loadBar").style.width="18%";$("loadText").textContent="Loading textures and character art…";try{await preload()}catch(e){console.error(e)}$("loadBar").style.width="65%";$("loadText").textContent="Building SANDLINE…";setTimeout(()=>{$("loadBar").style.width="100%";$("loadText").textContent="Deploying…";setTimeout(startMatch,220)},220)}
function newPlayer(){let s=team==="CT"?C.CT_SPAWN:C.T_SPAWN;let w=weapons[0];return{team,x:s.x,y:s.y,a:team==="CT"?-Math.PI/2:Math.PI/2,hp:100,armor:100,ammo:w.mag,reserve:w.reserve,reloading:false,alive:true,jump:0,jumpV:0,pitch:0,kills:0,bob:0}}
const CTN=["Falcon","Rook","Nova"],TN=["Raven","Blaze","Ghost"];
function bot(tm,i,x,y){return{team:tm,name:(tm==="CT"?CTN:TN)[i%3],x,y,a:0,hp:100,alive:true,path:[],pathAt:0,shot:.3+Math.random()*.6,plant:0,defuse:0}}
function resetRound(){ending=false;roundTime=105;bombPlanted=false;bombTimer=0;bomb=null;weaponIndex=0;player=newPlayer();bots=[];let cts=[[3.5,21.5],[2.5,20.5],[4.5,21.5]],ts=[[20.5,1.5],[21.5,2.5],[20.5,3.5]];let ci=0,ti=0;for(let i=0;i<3;i++){if(!(team==="CT"&&i===0))bots.push(bot("CT",ci++,cts[i][0],cts[i][1]));if(!(team==="T"&&i===0))bots.push(bot("T",ti++,ts[i][0],ts[i][1]))}$("msg").textContent="";updateHud()}
function startMatch(){loading.classList.add("hidden");hud.classList.remove("hidden");controls.classList.remove("hidden");ctScore=tScore=0;running=true;paused=false;resetRound();last=performance.now();requestAnimationFrame(loop)}
function addKill(s){let e=document.createElement("div");e.className="kill";e.textContent=s;$("feed").prepend(e);setTimeout(()=>e.remove(),2200)}
function showHit(){let h=$("hitmarker");h.classList.remove("on");void h.offsetWidth;h.classList.add("on")}
function showDamage(){let h=$("damageFlash");h.classList.remove("on");void h.offsetWidth;h.classList.add("on")}
function alive(tm){return(player.alive&&player.team===tm?1:0)+bots.filter(b=>b.alive&&b.team===tm).length}
function win(tm,why){if(ending)return;ending=true;tm==="CT"?ctScore++:tScore++;$("msg").textContent=(tm==="CT"?"COUNTER-TERRORISTS":"TERRORISTS")+" WIN · "+why;setTimeout(resetRound,2000)}
function checkWin(){if(ending)return;if(bombPlanted&&bombTimer<=0)return win("T","BOMB EXPLODED");if(!bombPlanted&&alive("T")===0)return win("CT","TEAM ELIMINATED");if(alive("CT")===0)return win("T","TEAM ELIMINATED");if(!bombPlanted&&roundTime<=0)return win("CT","TIME EXPIRED")}
function hurtPlayer(d,who){if(!player.alive)return;let absorb=Math.min(player.armor,d*.42);player.armor-=absorb;player.hp-=d-absorb*.45;showDamage();if(player.hp<=0){player.hp=0;player.alive=false;addKill(who+" ▸ YOU");$("msg").textContent="ELIMINATED"}}
function hurtBot(b,d,head){if(!b.alive)return;b.hp-=d;showHit();if(b.hp<=0){b.hp=0;b.alive=false;player.kills++;addKill("YOU ▸ "+b.name+(head?" · HEADSHOT":""));$("msg").textContent=head?"HEADSHOT":"ENEMY DOWN";setTimeout(()=>{if(!ending)$("msg").textContent=""},420)}}
function nearestEnemy(b){let arr=[];if(player.alive&&player.team!==b.team)arr.push(player);arr.push(...bots.filter(o=>o.alive&&o.team!==b.team));arr.sort((p,q)=>Math.hypot(p.x-b.x,p.y-b.y)-Math.hypot(q.x-b.x,q.y-b.y));return arr[0]||null}
function goto(b,gx,gy,dt){b.pathAt-=dt;if(b.pathAt<=0||b.path.length<2){b.path=C.path(b.x,b.y,gx,gy);b.pathAt=.35}if(b.path.length>1&&Math.hypot(b.x-b.path[1].x,b.y-b.path[1].y)<.25)b.path.shift();let p=b.path[1]||b.path[0];if(p){let a=Math.atan2(p.y-b.y,p.x-b.x);C.move(b,Math.cos(a)*dt*1.2,Math.sin(a)*dt*1.2,.17);b.a=a}}
function botAI(dt){for(let b of bots){if(!b.alive)continue;b.shot-=dt;let t=nearestEnemy(b);if(t){let d=Math.hypot(t.x-b.x,t.y-b.y);if(d<7.2&&C.los(b.x,b.y,t.x,t.y)){b.a=Math.atan2(t.y-b.y,t.x-b.x);if(b.shot<=0){b.shot=.62+Math.random()*.45;if(t===player)hurtPlayer(8+Math.random()*9,b.name);else{t.hp-=12+Math.random()*9;if(t.hp<=0){t.alive=false;addKill(b.name+" ▸ "+t.name)}}}if(d>3)goto(b,t.x,t.y,dt)}else goto(b,t.x,t.y,dt)}else{let g=b.team==="T"?{x:19,y:19}:{x:12,y:12};goto(b,g.x,g.y,dt)}
if(b.team==="T"&&!bombPlanted){let s=C.site(b.x,b.y);if(s){b.plant+=dt;if(b.plant>2){bombPlanted=true;bombTimer=30;bomb={x:b.x,y:b.y,label:s.label};$("msg").textContent="BOMB PLANTED";addKill(b.name+" PLANTED");b.plant=0}}}
if(b.team==="CT"&&bombPlanted&&Math.hypot(b.x-bomb.x,b.y-bomb.y)<1){b.defuse+=dt;if(b.defuse>4)return win("CT","BOMB DEFUSED")}else b.defuse=0}}
function currentWeapon(){return weapons[weaponIndex]}
function switchWeapon(){if(player.reloading)return;weaponIndex=(weaponIndex+1)%weapons.length;let w=currentWeapon();player.ammo=w.mag;player.reserve=w.reserve;updateHud()}
function reload(){let w=currentWeapon();if(w.mag===0||player.reloading||player.reserve<=0||player.ammo>=w.mag||!player.alive)return;player.reloading=true;$("msg").textContent="RELOADING";setTimeout(()=>{if(!player.reloading)return;let n=Math.min(w.mag-player.ammo,player.reserve);player.ammo+=n;player.reserve-=n;player.reloading=false;$("msg").textContent="";updateHud()},800)}
function shoot(){if(!running||paused||ending||!player.alive||player.reloading)return;let w=currentWeapon(),now=performance.now();if(now-lastShot<w.rate)return;lastShot=now;if(w.mag>0&&player.ammo<=0)return reload();if(w.mag>0)player.ammo--;
let best=null,bd=999,head=false;for(let b of bots){if(!b.alive||b.team===team)continue;let dx=b.x-player.x,dy=b.y-player.y,d=Math.hypot(dx,dy),a=Math.abs(C.norm(Math.atan2(dy,dx)-player.a));let hitRadius=Math.min(.115,.035+1.0/(d*34));if(d<=w.range&&a<hitRadius&&d<bd&&C.los(player.x,player.y,b.x,b.y)){best=b;bd=d;head=a<hitRadius*.34}}
if(best)hurtBot(best,head?w.head:w.damage,head);updateHud()}
function useAction(){if(!player.alive||ending)return;if(team==="T"&&!bombPlanted){let s=C.site(player.x,player.y);if(s){$("msg").textContent="PLANTING…";setTimeout(()=>{if(player.alive&&C.site(player.x,player.y)&&!bombPlanted){bombPlanted=true;bombTimer=30;bomb={x:player.x,y:player.y,label:s.label};$("msg").textContent="BOMB PLANTED"}},1700)}}else if(team==="CT"&&bombPlanted&&Math.hypot(player.x-bomb.x,player.y-bomb.y)<1.1){$("msg").textContent="DEFUSING…";setTimeout(()=>{if(player.alive&&bombPlanted&&Math.hypot(player.x-bomb.x,player.y-bomb.y)<1.1)win("CT","BOMB DEFUSED")},3400)}}
function updateHud(){let w=currentWeapon();$("hp").textContent=Math.max(0,Math.round(player.hp));$("armor").textContent=Math.max(0,Math.round(player.armor));$("weaponName").textContent=w.name;$("ammo").textContent=w.mag?player.ammo:"—";$("reserve").textContent=w.mag?player.reserve:"—";$("ctScore").textContent=ctScore;$("tScore").textContent=tScore;let t=bombPlanted?bombTimer:roundTime,m=Math.max(0,Math.floor(t/60)),s=Math.max(0,Math.floor(t%60));$("timer").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0");$("objective").textContent=bombPlanted?"BOMB PLANTED · SITE "+bomb.label:(team==="T"?"PLANT AT SITE A OR B":"DEFEND SITES A & B");let u=$("use");if(team==="T"&&!bombPlanted&&C.site(player.x,player.y)){u.style.display="block";u.textContent="PLANT"}else if(team==="CT"&&bombPlanted&&Math.hypot(player.x-bomb.x,player.y-bomb.y)<1.2){u.style.display="block";u.textContent="DEFUSE"}else u.style.display="none"}
function castRay(a){let dx=Math.cos(a),dy=Math.sin(a),mx=Math.floor(player.x),my=Math.floor(player.y),ddx=Math.abs(1/(dx||1e-8)),ddy=Math.abs(1/(dy||1e-8)),sx,sy,sdx,sdy;if(dx<0){sx=-1;sdx=(player.x-mx)*ddx}else{sx=1;sdx=(mx+1-player.x)*ddx}if(dy<0){sy=-1;sdy=(player.y-my)*ddy}else{sy=1;sdy=(my+1-player.y)*ddy}let side=0,ch="1";for(let i=0;i<80;i++){if(sdx<sdy){sdx+=ddx;mx+=sx;side=0}else{sdy+=ddy;my+=sy;side=1}ch=C.MAP[my]?.[mx]||"1";if(ch!=="0")break}let dist=side===0?(mx-player.x+(1-sx)/2)/(dx||1e-8):(my-player.y+(1-sy)/2)/(dy||1e-8);let wallX=side===0?player.y+dist*dy:player.x+dist*dx;wallX-=Math.floor(wallX);let tx=Math.floor(wallX*128);if(side===0&&dx>0)tx=127-tx;if(side===1&&dy<0)tx=127-tx;return{dist:Math.abs(dist),texX:tx,mat:ch,side}}
function texFor(mat){return mat==="2"?assets.concrete:mat==="3"?assets.metal:mat==="4"?assets.crate:assets.sand}
function drawWorld(){let horizon=H*.49+player.pitch+player.jump;let sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,"#7897a7");sky.addColorStop(1,"#c4b89f");ctx.fillStyle=sky;ctx.fillRect(0,0,W,horizon);let floor=ctx.createLinearGradient(0,horizon,0,H);floor.addColorStop(0,"#8c765a");floor.addColorStop(1,"#3d352d");ctx.fillStyle=floor;ctx.fillRect(0,horizon,W,H-horizon);
let z=[];for(let x=0,zi=0;x<W;x+=STRIP,zi++){let a=player.a-FOV/2+FOV*x/W,r=castRay(a),d=r.dist*Math.cos(a-player.a),wh=Math.min(H*2,H*.88/Math.max(.1,d)),y=horizon-wh/2,img=texFor(r.mat);z[zi]=d;if(img)ctx.drawImage(img,r.texX,0,1,128,x,y,STRIP+1,wh);else{ctx.fillStyle="#8b765a";ctx.fillRect(x,y,STRIP+1,wh)}if(r.side===1){ctx.fillStyle="rgba(0,0,0,.12)";ctx.fillRect(x,y,STRIP+1,wh)}}
let spr=[];for(let b of bots)if(b.alive){let d=Math.hypot(b.x-player.x,b.y-player.y),a=C.norm(Math.atan2(b.y-player.y,b.x-player.x)-player.a);if(Math.abs(a)<FOV*.66&&C.los(player.x,player.y,b.x,b.y))spr.push({b,d,a})}spr.sort((p,q)=>q.d-p.d);
for(let s of spr){let img=s.b.team==="CT"?assets.ct:assets.t,sx=W/2+Math.tan(s.a)/Math.tan(FOV/2)*(W/2),sh=Math.min(H*.9,H*.72/s.d),sw=sh*(img.width/img.height),left=sx-sw/2,top=horizon-sh*.72;for(let x=Math.max(0,left);x<Math.min(W,left+sw);x+=STRIP){let zi=Math.floor(x/STRIP);if(s.d<(z[zi]||999)){let tx=Math.floor((x-left)/sw*img.width);ctx.drawImage(img,tx,0,1,img.height,x,top,STRIP+1,sh)}}}
if(bombPlanted&&assets.bomb){let d=Math.hypot(bomb.x-player.x,bomb.y-player.y),a=C.norm(Math.atan2(bomb.y-player.y,bomb.x-player.x)-player.a);if(Math.abs(a)<FOV*.65&&C.los(player.x,player.y,bomb.x,bomb.y)){let sx=W/2+Math.tan(a)/Math.tan(FOV/2)*W/2,sz=Math.min(52,H*.22/d);ctx.drawImage(assets.bomb,sx-sz/2,horizon+sz*.15,sz,sz)}}
let w=currentWeapon(),img=assets[w.img];if(img){let bob=Math.sin(player.bob)*5,kick=performance.now()-lastShot<70?11:0,scale=w.img==="rifle"?.76:w.img==="pistol"?.72:.66,dw=W*scale,dh=dw*(img.height/img.width);if(dh>H*.78){let k=(H*.78)/dh;dw*=k;dh*=k}ctx.drawImage(img,W-dw+W*.03,H-dh+bob+kick+player.jump*.18,dw,dh);if(performance.now()-lastShot<45){ctx.save();ctx.globalCompositeOperation="lighter";let gx=W*.82,gy=H*.51;ctx.fillStyle="rgba(255,219,92,.9)";ctx.beginPath();for(let i=0;i<10;i++){let a=i*Math.PI/5,r=i%2?8:25;let x=gx+Math.cos(a)*r,y=gy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.fill();ctx.restore()}}}
function currentGoal(b){if(b.team==="T"&&!bombPlanted)return{x:19.5,y:19.5};if(b.team==="CT"&&bombPlanted)return bomb;return{x:12,y:12}}
function tickAI(dt){botAI(dt)}
let jid=null,lid=null,lx=0,ly=0,joy=$("joy"),stick=$("stick"),look=$("look");
function setJoy(x,y){let r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=x-cx,dy=y-cy,max=r.width*.33,l=Math.hypot(dx,dy)||1,k=Math.min(1,max/l);dx*=k;dy*=k;input.jx=dx/max;input.jy=dy/max;stick.style.transform=`translate(${dx}px,${dy}px)`}
function stopJoy(){jid=null;input.jx=input.jy=0;stick.style.transform="translate(0,0)"}
joy.addEventListener("pointerdown",e=>{jid=e.pointerId;joy.setPointerCapture?.(e.pointerId);setJoy(e.clientX,e.clientY)});joy.addEventListener("pointermove",e=>{if(e.pointerId===jid)setJoy(e.clientX,e.clientY)});joy.addEventListener("pointerup",stopJoy);joy.addEventListener("pointercancel",stopJoy);
look.addEventListener("pointerdown",e=>{lid=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture?.(e.pointerId)});look.addEventListener("pointermove",e=>{if(e.pointerId!==lid)return;let dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;player.a+=dx*.004;player.pitch=Math.max(-30,Math.min(30,player.pitch+dy*.09))});look.addEventListener("pointerup",()=>lid=null);look.addEventListener("pointercancel",()=>lid=null);
$("fire").onpointerdown=e=>{e.preventDefault();shoot();let iv=setInterval(shoot,currentWeapon().rate);let stop=()=>{clearInterval(iv);$("fire").removeEventListener("pointerup",stop);$("fire").removeEventListener("pointercancel",stop)};$("fire").addEventListener("pointerup",stop);$("fire").addEventListener("pointercancel",stop)};
$("reload").onpointerdown=e=>{e.preventDefault();reload()};$("jump").onpointerdown=e=>{e.preventDefault();if(player.alive&&!player.jump&&!player.jumpV)player.jumpV=-225};$("use").onpointerdown=e=>{e.preventDefault();useAction()};$("switch").onpointerdown=e=>{e.preventDefault();switchWeapon()};$("menu").onclick=()=>{paused=true;$("pause").classList.remove("hidden")};$("resume").onclick=()=>{paused=false;$("pause").classList.add("hidden");last=performance.now()};$("leave").onclick=()=>{running=false;paused=false;$("pause").classList.add("hidden");hud.classList.add("hidden");controls.classList.add("hidden");portal.classList.remove("hidden")};
const keys={};addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==="r")reload();if(e.key==="1"){weaponIndex=0;updateHud()}if(e.key==="2"){weaponIndex=1;updateHud()}if(e.key==="3"){weaponIndex=2;updateHud()}if(e.code==="Space")shoot()});addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
function loop(t){if(!running)return;let dt=Math.min(.04,(t-last)/1000||0);last=t;if(!paused&&!ending){let kx=(keys.d?1:0)-(keys.a?1:0),ky=(keys.s?1:0)-(keys.w?1:0),mx=Math.max(-1,Math.min(1,input.jx+kx)),my=Math.max(-1,Math.min(1,input.jy+ky)),sp=3.35*dt,fx=Math.cos(player.a),fy=Math.sin(player.a),rx=Math.cos(player.a+Math.PI/2),ry=Math.sin(player.a+Math.PI/2),moving=Math.abs(mx)+Math.abs(my)>.08;if(player.alive)C.move(player,(fx*(-my)+rx*mx)*sp,(fy*(-my)+ry*mx)*sp,.19);if(moving)player.bob+=dt*9;if(player.jumpV||player.jump){player.jump+=player.jumpV*dt;player.jumpV+=780*dt;if(player.jump>0){player.jump=0;player.jumpV=0}}if(bombPlanted)bombTimer-=dt;else roundTime-=dt;tickAI(dt);checkWin();updateHud()}drawWorld();requestAnimationFrame(loop)}
window.__hobileDebug={getPlayer:()=>({...player}),getBots:()=>bots.map(b=>({...b})),startCT:()=>{team="CT";portal.classList.add("hidden");teams.classList.add("hidden");loading.classList.add("hidden");hud.classList.remove("hidden");controls.classList.remove("hidden");ctScore=tScore=0;running=true;paused=false;resetRound();last=performance.now();requestAnimationFrame(loop)},faceNearestEnemy:()=>{let e=bots.filter(b=>b.alive&&b.team!==team).sort((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)-Math.hypot(b.x-player.x,b.y-player.y))[0];if(e)player.a=Math.atan2(e.y-player.y,e.x-player.x)},teleportNearEnemy:()=>{let e=bots.find(b=>b.alive&&b.team!==team);if(e){player.x=e.x-1.7;player.y=e.y;player.a=0}},shoot,resetRound};
})();
