const assert=require("assert");
const C=require("./net-core.js");
let seq=[0,.1,.2,.3,.4],i=0;
assert.strictEqual(C.makeRoomCode(()=>seq[i++]),"ADGKN");
const state={a:[{id:"a",creator:true,joinedAt:20,team:"CT"}],b:[{id:"b",creator:false,joinedAt:10,team:"T"}]};
const p=C.flattenPresence(state);
assert.strictEqual(p.length,2);
assert.strictEqual(C.electHost(p),"a");
assert.strictEqual(C.teamAlive([{team:"CT",alive:true},{team:"CT",alive:false},{team:"T",alive:true}],"CT"),1);
const shooter={x:0,z:0,y:1.65,yaw:0,team:"CT",alive:true};
const target={x:0,z:-5,y:1.65,team:"T",alive:true};
assert(C.validateHit(shooter,target,{yaw:0}));
assert(!C.validateHit(shooter,{...target,team:"CT"},{yaw:0}));
assert(!C.validateHit(shooter,{...target,x:20,z:0},{yaw:0}));
console.log("PASS room code");
console.log("PASS presence flatten");
console.log("PASS creator host election");
console.log("PASS team alive count");
console.log("PASS host hit validation");
console.log("6/6 networking core checks passed");